#! /bin/sh
bspc rule -r "*"

# STARTUP

xrandr --output eDP-1-1 --primary --mode 1920x1080 --rotate normal &
picom &
pgrep -x sxhkd > /dev/null || sxhkd -m 1 &
xinput set-prop 'MSFT0001:01 06CB:CD5F Touchpad' 'libinput Tapping Enabled' 1 &
xset s off -dpms &
setxkbmap -option caps:swapescape &
nitrogen --restore &
killall "blueman-applet" 
blueman-applet &
killall "nm-applet"
nm-applet &
killall "udiskie"
udiskie -t &
dash /home/tudorcelstan/scripts/launch.sh &

# DESKTOPS

bspc monitor -d Edit Web Mess File Txt Mp3
# bspc monitor eDP-1-1 -d Edit Web Mess File Txt Mp3 
# bspc monitor HDMI-0 -d TV

# GLOBAL SETTINGS

bspc config single_monocle			on
bspc config remove_unplugged_monitors		true
bspc config remove_disabled_monitors		true
bspc config click_to_focus none
bspc config focus_follows_pointer true

# BORDERS

bspc config normal_border_color   "#3A3A3A"
# bspc config focused_border_color    "#CB9A69"
bspc config border_width         2
bspc config window_gap         0 
bspc config top_padding     23

# LAYOUTS

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# WINDOW RULES

bspc rule -a qutebrowser desktop='^2' follow=on
bspc rule -a Surf state=tiled desktop='^2' follow=on
bspc rule -a Zathura state=tiled follow=on
bspc rule -a Epiphany desktop='^2' follow=on
bspc rule -a darktable state=fullscreen
bspc rule -a Darktable desktop='^1' state=fullscreen follow=on
bspc rule -a Signal desktop='^3' follow=on
bspc rule -a mplayer2 state=floating
bspc rule -a Gcolor3 state=floating sticky=on
bspc rule -a mpv Media Player sticky=on
bspc rule -a Screenkey manage=off
